version: '3'

services:

  postgres:
    build:
      context: ./
      dockerfile: postgres.dockerfile
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: miningcore
      POSTGRES_PASSWORD: miningcore
      POSTGRES_DB: miningcore

  ocash-node:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ocash-node.dockerfile
        # args:
        #   - POOL_ADDRESS=${POOL_ADDRESS}
    ports:
      # it is important to keep Geth RPC api only exposed to localhost
      # it will be reachable by miningcore but not open to internet which
      # is catastrophic with --allow-insecure-unlock
      - 127.0.0.1:8545:8545
      - 30303:30303
    command:
      [
        "--rpc.allow-unprotected-txs",
        "--http",
        "--http.addr=0.0.0.0",
        "--http.corsdomain=*",
        "--http.api=eth,net,web3",
        "--http.vhosts=*",
        "--allow-insecure-unlock",
        "--unlock=${POOL_ADDRESS}",
        "--password=${KEYSTORE_PASSWORD_FILE_PATH}",
        "--ws",
        "--ws.addr=0.0.0.0",
        "--ws.origins=*",
        "--ws.api=eth,net,web3",
        "--networkid=660868",
        "--txlookuplimit=0",
        "--mine",
        "--nat=extip:210.178.106.171",
        "--snapshot=false",
        "--syncmode=full",
        "--gcmode=archive",
        "--txpool.lifetime=3h5m0s",
        "--miner.etherbase=${POOL_ADDRESS}",
        # "--miner.gasprice=1000000000" ,
        # "--miner.gaslimit=500000000000",
        # "--override.terminaltotaldifficulty=500000000000000000",
        # "--override.terminaltotaldifficultypassed=false",
        "--bootnodes=enode://b164ae2b30e39642a3e1c22e545f92b34a7ff6047d9a3a14e99598ec17896d9f6512ce40a326fdd1574485a597d419a28d53b70de18ba324efada01c7050da6a@210.178.106.171:30303",
        # "--cache=8192",
        # "--metrics",
        # "--maxpeers=30",
      ]
    volumes:
      - geth-data:/root/.ethereum
      - ${KEYSTORE_DIR_PATH}:/root/.ethereum/keystore
      - ${KEYSTORE_PASSWORD_FILE_PATH}:/root/.ethereum/pw.txt:ro

  miningcore:
    # uncomment to run on macOS arm
    # platform: linux/amd64
    build:
      context: ./
      dockerfile: miningcore.dockerfile
    ports:
      # - 3032-3199:3032-3199
      - 4000:4000
      - 4073:4073
    volumes:
      - ./config/config.json:/config.json
      - ${POOL_TLS_CERT_PATH}:/var/lib/certs/cert.pfx:ro
      - miningcore-data:/usr/local/miningcore-data/
      - ./config/coins.json:/usr/local/miningcore/coins.json
    command:
      [
        "-c /config.json",
      ]
    depends_on:
      - ocash-node
      - postgres

  # TODO dockerfile, forked from Caddy image
  # miningcore-ui:
  #   build:
  #     context: ./
  #     dockerfile: miningcore.dockerfile
  #   ports:
  #     - 8080:80
  #   environment:
  #     - API_URL=http://localhost:4000/api
  #     - DEFAULT_POOL=eth1
  #   depends_on:
  #     - miningcore

volumes:
  postgres-data:
  geth-data:
  miningcore-data:
